### ISSUE TITLE
JavaScript: Dynamic Search Bar on All Pages

### ISSUE THREAD

**Issue by PrabhavPandey** [itskeshavdubey/SNUxplore#1]
Implement a JS based search to **filter** through the contents on a particular page
For example, on the residentials page, if I type in 1A, the only tile that should be visible should is this:

![image](https://user-images.githubusercontent.com/18113725/147571833-ff0d7590-81a8-49df-bb7c-cc87be1541cf.png)

The frontend (HTML and CSS) has already been completed as you can see above.

**Comment by PrabhavPandey** [comment]
Merged the changes. The search works flawlessly. 

Would be great if you could try to add the **background color** to the icon so that it matches the previous design (_as shown in the issue description above_).

Excepting a few bugs and styling issues, briliant work @yathansh13!

**Comment by itskeshavdubey** [comment]
Great work Yathansh!👍
